# Generated by Django 5.1.2 on 2024-10-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraduateProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("graduate_program", models.CharField(max_length=100)),
                ("university", models.CharField(max_length=100)),
                ("language", models.CharField(max_length=50)),
                ("degree", models.CharField(max_length=50)),
                ("gpa", models.DecimalField(decimal_places=2, max_digits=3)),
                ("additional_requirements", models.TextField()),
                ("country", models.CharField(max_length=100)),
            ],
        ),
    ]
