# Generated by Django 5.0.9 on 2024-10-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="graduateprogram",
            name="additional_requirements",
        ),
        migrations.RemoveField(
            model_name="graduateprogram",
            name="gpa",
        ),
        migrations.AddField(
            model_name="graduateprogram",
            name="qualifications",
            field=models.JSONField(null=True),
        ),
    ]
